Modified configure.ac to only define XRENDER (and thus check for 32 bit surfaces) if we use it with Cairo, as backart has trouble with it.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/back/trunk@25444 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6880,84 +6880,6 @@ _ACEOF
 fi
 
 #--------------------------------------------------------------------
-# XRender support
-#--------------------------------------------------------------------
-have_xrender=no
-{ echo "$as_me:$LINENO: checking for XRenderFindVisualFormat in -lXrender" >&5
-echo $ECHO_N "checking for XRenderFindVisualFormat in -lXrender... $ECHO_C" >&6; }
-if test "${ac_cv_lib_Xrender_XRenderFindVisualFormat+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lXrender  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char XRenderFindVisualFormat ();
-int
-main ()
-{
-return XRenderFindVisualFormat ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_Xrender_XRenderFindVisualFormat=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_Xrender_XRenderFindVisualFormat=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_Xrender_XRenderFindVisualFormat" >&5
-echo "${ECHO_T}$ac_cv_lib_Xrender_XRenderFindVisualFormat" >&6; }
-if test $ac_cv_lib_Xrender_XRenderFindVisualFormat = yes; then
-  have_xrender=yes
-fi
-
-if test "$have_xrender" = yes; then
-
-cat >>confdefs.h <<\_ACEOF
-#define XRENDER 1
-_ACEOF
-
-  LIBS="$LIBS -lXrender"
-fi
-
-#--------------------------------------------------------------------
 # Window's graphics library
 #--------------------------------------------------------------------
 { echo "$as_me:$LINENO: checking for main in -lgdi32" >&5
@@ -8078,6 +8000,87 @@ echo "${ECHO_T}$CAIRO_GLITZ_LIBS" >&6; }
   fi
 
 
+#--------------------------------------------------------------------
+# XRender support
+#--------------------------------------------------------------------
+
+have_xrender=no
+{ echo "$as_me:$LINENO: checking for XRenderFindVisualFormat in -lXrender" >&5
+echo $ECHO_N "checking for XRenderFindVisualFormat in -lXrender... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Xrender_XRenderFindVisualFormat+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXrender  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char XRenderFindVisualFormat ();
+int
+main ()
+{
+return XRenderFindVisualFormat ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_Xrender_XRenderFindVisualFormat=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_Xrender_XRenderFindVisualFormat=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Xrender_XRenderFindVisualFormat" >&5
+echo "${ECHO_T}$ac_cv_lib_Xrender_XRenderFindVisualFormat" >&6; }
+if test $ac_cv_lib_Xrender_XRenderFindVisualFormat = yes; then
+  have_xrender=yes
+fi
+
+if test "$have_xrender" = yes; then
+  # we'll use it only if we want cairo
+  if test x"$BUILD_GRAPHICS" = "xcairo"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define XRENDER 1
+_ACEOF
+
+    LIBS="$LIBS -lXrender"
+  fi
+fi
 
 #--------------------------------------------------------------------
 # Glitz libraries
