* ChangeLog 	* config.h.in 	* configure 	* configure.ac 	* Headers/win32/WIN32Server.h 	* Source/cairo/CairoContext.m 	* Source/cairo/CairoGState.m 	* Source/cairo/CairoPDFSurface.m 	* Source/cairo/GNUmakefile 	* Source/cairo/Win32CairoSurface.m 	* Source/GSBackend.m 	* Source/gsc/GSGState.m 	* Source/win32/w32_create.m 	* Source/win32/w32_general.m 	* Source/win32/w32_GLcontext.m 	* Source/win32/w32_movesize.m 	* Source/win32/w32_windowdisplay.m 	* Source/win32/WIN32Server.m 	* Source/winlib/GNUmakefile.preamble: Merge of all testplant 	branch changes to trunk for Cairo changes.  Did code cleanup to 	make the code conform to coding standards.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/back/trunk@35821 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -613,6 +613,8 @@ GLITZ_GLX_LIBS
 GLITZ_GLX_CFLAGS
 GLITZ_LIBS
 GLITZ_CFLAGS
+FONTCONFIG_LIBS
+FONTCONFIG_CFLAGS
 CAIRO_GLITZ_LIBS
 CAIRO_GLITZ_CFLAGS
 CAIRO_WIN32_LIBS
@@ -5584,6 +5586,45 @@ fi
 if test "$have_msimg32" = yes; then
   WIN32_LIBS="${WIN32_LIBS} -lmsimg32"
 fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -limm32" >&5
+$as_echo_n "checking for main in -limm32... " >&6; }
+if ${ac_cv_lib_imm32_main+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-limm32  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_imm32_main=yes
+else
+  ac_cv_lib_imm32_main=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_imm32_main" >&5
+$as_echo "$ac_cv_lib_imm32_main" >&6; }
+if test "x$ac_cv_lib_imm32_main" = xyes; then :
+  have_imm32=yes
+else
+  have_imm32=no
+fi
+
+if test "$have_imm32" = yes; then
+  WIN32_LIBS="${WIN32_LIBS} -limm32"
+fi
 
 #--------------------------------------------------------------------
 # WGL support
@@ -6251,6 +6292,106 @@ $as_echo "$CAIRO_GLITZ_LIBS" >&6; }
      have_cairo_glitz=no
   fi
 
+PKG_FONTCONFIG=no
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "pkg-config script not be found"
+     ## We don't want the user to see this warning
+     ## echo "*** The pkg-config script could not be found. Make sure it is"
+     ## echo "*** in your path, or set the PKG_CONFIG environment variable"
+     ## echo "*** to the full path to pkg-config."
+     ## echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: checking for fontconfig" >&5
+$as_echo_n "checking for fontconfig... " >&6; }
+
+        if $PKG_CONFIG --exists "fontconfig" ; then
+            { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+            succeeded=yes
+
+            { $as_echo "$as_me:${as_lineno-$LINENO}: checking FONTCONFIG_CFLAGS" >&5
+$as_echo_n "checking FONTCONFIG_CFLAGS... " >&6; }
+            FONTCONFIG_CFLAGS=`$PKG_CONFIG --cflags "fontconfig"`
+            { $as_echo "$as_me:${as_lineno-$LINENO}: result: $FONTCONFIG_CFLAGS" >&5
+$as_echo "$FONTCONFIG_CFLAGS" >&6; }
+
+            { $as_echo "$as_me:${as_lineno-$LINENO}: checking FONTCONFIG_LIBS" >&5
+$as_echo_n "checking FONTCONFIG_LIBS... " >&6; }
+            FONTCONFIG_LIBS=`$PKG_CONFIG --libs "fontconfig"`
+            { $as_echo "$as_me:${as_lineno-$LINENO}: result: $FONTCONFIG_LIBS" >&5
+$as_echo "$FONTCONFIG_LIBS" >&6; }
+        else
+            FONTCONFIG_CFLAGS=""
+            FONTCONFIG_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            FONTCONFIG_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "fontconfig"`
+
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     have_fontconfig=yes
+  else
+     have_fontconfig=no
+  fi
+
 
 if test "$have_cairo" = no; then
   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for cairo_create in -lcairo" >&5
@@ -6916,11 +7057,21 @@ $as_echo "$as_me: WARNING: can't find cairo, required for graphics=cairo!" >&2;}
     fi
     { $as_echo "$as_me:${as_lineno-$LINENO}: Switching to $BUILD_GRAPHICS" >&5
 $as_echo "$as_me: Switching to $BUILD_GRAPHICS" >&6;}
+  elif test $BUILD_SERVER = win32 -a "$have_fontconfig" = no ; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: can't find fontconfig, required for graphics=cairo!" >&5
+$as_echo "$as_me: WARNING: can't find fontconfig, required for graphics=cairo!" >&2;}
+    BUILD_GRAPHICS=winlib
+    { $as_echo "$as_me:${as_lineno-$LINENO}: Switching to $BUILD_GRAPHICS" >&5
+$as_echo "$as_me: Switching to $BUILD_GRAPHICS" >&6;}
   else
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking Cairo backend" >&5
 $as_echo_n "checking Cairo backend... " >&6; }
     CAIRO_LIBS="$CAIRO_FT_LIBS"
     CAIRO_CFLAGS="$CAIRO_FT_CFLAGS"
+    if test $BUILD_SERVER = win32; then
+      CAIRO_LIBS="$CAIRO_LIBS $FONTCONFIG_LIBS"
+      CAIRO_CFLAGS="$CAIRO_CFLAGS $FONTCONFIG_CFLAGS"
+    fi
 
     if test "$have_xrender" = yes; then
       if test $BUILD_SERVER = x11 -a "x$have_cairo_xlib" = "xyes"; then
@@ -6957,10 +7108,8 @@ $as_echo "$as_me: WARNING: **** Are you a backend developer ?" >&2;}
       CAIRO_CFLAGS="$CAIRO_CFLAGS $CAIRO_WIN32_CFLAGS"
       { $as_echo "$as_me:${as_lineno-$LINENO}: result: winlib" >&5
 $as_echo "winlib" >&6; }
-      { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: **** Cairo backend on win32 is experimental and is not supported." >&5
-$as_echo "$as_me: WARNING: **** Cairo backend on win32 is experimental and is not supported." >&2;}
-      { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: **** Are you a backend developer ?" >&5
-$as_echo "$as_me: WARNING: **** Are you a backend developer ?" >&2;}
+      #AC_MSG_WARN([**** Cairo backend on win32 is experimental and is not supported.])
+      #AC_MSG_WARN([**** Are you a backend developer ?])
     elif test $BUILD_SERVER = x11 -a "x$have_cairo_xlib" = "xyes"; then
       CAIRO_LIBS="$CAIRO_LIBS $CAIRO_XLIB_LIBS $XFT_LIBS"
       CAIRO_CFLAGS="$CAIRO_CFLAGS $CAIRO_XLIB_CFLAGS"
@@ -7057,7 +7206,7 @@ _ACEOF
 
 
 cat >>confdefs.h <<_ACEOF
-#define BUILD_GRAPHICS $BUILD_GRAPHICS
+#define BUILD_GRAPHICS GRAPHICS_$BUILD_GRAPHICS
 _ACEOF
 
 
